# Generated by Django 3.2.6 on 2021-09-09 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulator_groups', '0003_auto_20210909_1016'),
        ('simulators', '0010_simulator_pay_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorEmails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.PositiveIntegerField(choices=[(0, 'Регистрация'), (1, 'Покупка'), (2, 'Покупка отклонена'), (3, 'Автоматическая регистрация')], default=0)),
                ('template', models.TextField()),
                ('theme', models.CharField(max_length=255)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulator_groups.simulatorgroup')),
                ('simulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulators.simulator')),
            ],
        ),
    ]
