# Generated by Django 3.2.6 on 2021-09-07 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulators', '0007_simulatoruser'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=40)),
                ('text', models.TextField(blank=True, null=True)),
                ('price', models.PositiveIntegerField()),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(('app_label', 'api_admin'), ('model', 'simulator')), null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='contenttypes.contenttype')),
                ('simulator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='simulators.simulator')),
                ('user_set', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('sum', models.PositiveIntegerField()),
                ('return_url', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('confirmation_url', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentId', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.IntegerField(choices=[(0, 'canceled'), (1, 'pending'), (2, 'succeeded')], default=1)),
                ('backend', models.CharField(choices=[('tinkoff', 'tinkoff'), ('cloudpayments', 'cloudpayments')], max_length=30)),
                ('content_type', models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(('app_label', 'api_admin'), ('model', 'simulator')), null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='contenttypes.contenttype')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulators.simulatoruser')),
            ],
        ),
    ]
