# Generated by Django 3.2.6 on 2021-09-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymentId',
            new_name='payment_id',
        ),
    ]
