# Generated by Django 3.2.3 on 2021-08-01 21:51

from django.conf import settings
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_page_places'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[('content', 'theory'), ('content', 'question'), ('content', 'message'), ('content', 'safetext'), ('content', 'openquestion'), ('content', 'test'), ('content', 'openquestionexpert'), ('content', 'questionanswercheck')], default=0)),
                ('text', models.TextField(blank=True, null=True)),
                ('female_text', models.TextField(blank=True, null=True)),
                ('text_description', models.TextField(blank=True, null=True)),
                ('postreply_text', models.TextField(blank=True, null=True)),
                ('postreply_female_text', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('comment_number', models.IntegerField(blank=True, null=True)),
                ('comment_advice', models.TextField(blank=True, null=True)),
                ('comment_female_advice', models.TextField(blank=True, null=True)),
                ('script_id', models.CharField(blank=True, max_length=300, null=True)),
                ('script_text', models.TextField(blank=True, null=True)),
                ('need_notifications', models.BooleanField(blank=True, null=True)),
                ('award', models.IntegerField(blank=True, null=True)),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('parent_message', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('answer', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('comments', django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
