# Generated by Django 3.2.3 on 2021-08-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_next_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('theory', 'Теория'), ('question', 'Вовпрос'), ('message', 'Сообщение'), ('safetext', 'Текст'), ('openquestion', 'Открытый вопрос'), ('test', 'Тест'), ('openquestionexpert', 'Открытый вопрос эксперту'), ('questionanswercheck', 'Открытый вопрос с проверкой')], default='theory', max_length=200),
        ),
    ]
