# Generated by Django 3.2.3 on 2021-08-18 18:23

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20210818_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='node_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
