# Generated by Django 3.2.3 on 2021-08-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_node_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('theory', 'Теория'), ('question', 'Вовпрос'), ('message', 'Сообщение'), ('safetext', 'Текст'), ('openquestion', 'Открытый вопрос'), ('test', 'Тест'), ('openquestionexpert', 'Открытый вопрос эксперту'), ('questionanswercheck', 'Открытый вопрос с проверкой')], max_length=200),
        ),
    ]
