# Generated by Django 3.2.3 on 2021-08-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('places', '0007_place_theory_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characters.character'),
        ),
        migrations.AlterField(
            model_name='place',
            name='type',
            field=models.CharField(choices=[('theory', 'Теория'), ('question', 'Вовпрос'), ('message', 'Сообщение'), ('safetext', 'Текст'), ('openquestion', 'Открытый вопрос'), ('test', 'Тест'), ('openquestionexpert', 'Открытый вопрос эксперту'), ('questionanswercheck', 'Открытый вопрос с проверкой'), ('questionuserchoice', 'Вопрос с выбором пользователя')], max_length=200),
        ),
    ]
