# Generated by Django 3.2.3 on 2021-08-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_place_points_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_current_user',
            field=models.BooleanField(default=False),
        ),
    ]
