# Generated by Django 3.2.3 on 2021-08-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_place_is_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
