# Generated by Django 3.2.7 on 2021-09-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_auto_20210826_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
