# Generated by Django 3.2.3 on 2021-09-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_place_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='points',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='points_error',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
