# Generated by Django 3.2.3 on 2021-09-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_auto_20210906_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='points_error',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
