# Generated by Django 3.2.3 on 2021-06-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_sequence_no'),
        ('pages', '0002_alter_page_sequence_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='simulator',
        ),
        migrations.AlterField(
            model_name='page',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
