# Generated by Django 3.2.3 on 2021-08-01 21:51

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210627_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='places',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
