# Generated by Django 3.2.3 on 2021-08-01 23:18

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='next_pages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
