# Generated by Django 3.2.3 on 2021-08-18 20:11

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_next_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='links',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
