# Generated by Django 3.2.3 on 2021-08-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='is_start',
            field=models.BooleanField(default=False),
        ),
    ]
