# Generated by Django 3.2.3 on 2021-08-27 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_userlessonprogress_start_at'),
        ('simulators', '0007_simulatoruser'),
        ('pages', '0007_auto_20210826_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_onboarding',
        ),
        migrations.AddField(
            model_name='page',
            name='is_onboarding_for',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='simulators.simulator'),
        ),
        migrations.AlterField(
            model_name='page',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
