# Generated by Django 3.2.3 on 2021-08-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_userlessonprogress_start_at'),
        ('pages', '0008_auto_20210827_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='lessons.lesson'),
        ),
    ]
