# Generated by Django 3.2.3 on 2021-09-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_userpageprogress_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpageprogress',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
