# Generated by Django 3.2.3 on 2021-09-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_userpageprogress_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpageprogress',
            name='next_page',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
