# Generated by Django 3.2.3 on 2021-08-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulatorgroup',
            name='name',
            field=models.CharField(default='Основная группа', max_length=200),
        ),
    ]
