# Generated by Django 3.2.6 on 2021-09-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_groups', '0002_alter_simulatorgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulatorgroup',
            name='auth_facebook_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulatorgroup',
            name='auth_facebook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulatorgroup',
            name='auth_vk_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulatorgroup',
            name='auth_vk_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
