# Generated by Django 3.2.3 on 2021-08-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_admin_user',
            field=models.BooleanField(default=False),
        ),
    ]
