# Generated by Django 3.2.7 on 2021-09-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_userlessonprogress_pages'),
        ('user_profile', '0003_authattempt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id_admin_user',
            new_name='is_admin_user',
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_action',
            field=models.IntegerField(choices=[(-2, 'Регистрация'), (-1, 'Создание персонажа'), (0, 'Онбординг'), (1, 'Прохождение урока')], default=-2),
        ),
        migrations.AddField(
            model_name='user',
            name='last_action_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='temporary_code',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
