# Generated by Django 3.2.3 on 2021-08-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('simulators', '0006_auto_20210815_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='TheoryChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sequence_no', models.PositiveIntegerField()),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulators.simulator')),
            ],
        ),
    ]
