# Generated by Django 3.2.3 on 2021-08-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0003_alter_simulator_sequence_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='facebook',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='main_color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='message_after_chapter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='message_after_task',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='pay_EmailCompany',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='pay_TerminalKey',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='pay_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='telegram',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='text_button_after_chapter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='vkontakte',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='welcome_message_author_img',
            field=models.ImageField(blank=True, null=True, upload_to='simulator_images'),
        ),
        migrations.AddField(
            model_name='simulator',
            name='welcome_message_author_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='welcome_message_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='SimulatorSetting',
        ),
    ]
