# Generated by Django 3.2.3 on 2021-08-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0004_auto_20210802_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='message_award',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='need_pause',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='openquestion_award',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='openquestionexpert_award',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='pause_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='pause_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='question_award_correct',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='question_award_error',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='questionanswercheck_award_correct',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='questionanswercheck_award_error',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='questionuserchoice_award',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='random_icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='random_link',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='random_showing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='random_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='recommended_volume',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='safetext_award',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='test_award_correct',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='test_award_error',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='simulator',
            name='theory_award',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
