# Generated by Django 3.2.3 on 2021-08-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0005_auto_20210815_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='domain',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
