# Generated by Django 3.2.3 on 2021-08-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lessons', '0005_userlessonprogress_start_at'),
        ('pages', '0007_auto_20210826_1404'),
        ('simulators', '0006_auto_20210815_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('simulator_paid', models.BooleanField(default=False)),
                ('simulator_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('current_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page')),
                ('first_uncompleted_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lesson')),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulators.simulator')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
