# Generated by Django 3.2.3 on 2021-09-07 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0008_simulator_show_page_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
