# Generated by Django 3.2.6 on 2021-09-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulators', '0009_simulator_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='pay_type',
            field=models.CharField(choices=[('tinkoff', 'tinkoff'), ('cloudpayments', 'cloudpayments')], default='tinkoff', max_length=255),
        ),
    ]
