# Generated by Django 3.2.3 on 2021-06-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_userlessonprogress_first_uncompleted_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='sequence_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
