# Generated by Django 3.2.3 on 2021-08-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_sequence_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='need_pause',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pause_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='pause_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.PositiveIntegerField(default=5000),
        ),
    ]
