# Generated by Django 3.2.3 on 2021-08-30 18:41

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_userlessonprogress_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='pages',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
